# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_bc0dd7d4ed4041d4725318c29f90effef1fb4943

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/dist/**,client/public/**,.scannerwork/**,**/__tests__/**

sonar.tests=__tests__,client/src/__tests__
sonar.test.inclusions=**/*.test.js,**/*.spec.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info