# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=sqp_f8925cbd8654956df06bef97340260ae34c530f3

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=.

sonar.javascript.lcov.reportPaths=coverage/server/lcov.info,coverage/client/lcov.info

sonar.language=js

sonar.inclusions=client/src/**/*.js,config/*.js,controllers/*.js,helpers/*.js,middlewares/*.js,models/*.js

sonar.exclusions=**/**.test.js,client/src/_site/,client/src/App.js,client/src/index.js,client/src/setupTests.js,client/src/reportWebVitals.js,setupTests.js